version: '2'

networks:
  macvlan-samba:
    external:
      name: pihole_pihole_network
services:

 samba-member:
  build: .
  container_name: samba-member
  ports:
   - "1812:1812/udp"
   - "1813:1813"
   - "18120:18120"
  dns_search:
   - ad.chaos
  dns:
   - 192.168.1.45
   - 192.168.1.6
  environment:
   - DOMAIN=AD.CHAOS
   - DOMAINUSER=Administrator
   - DOMAINPASS=Pa!!word1
   - LOG_LEVEL=3
   - WINBIND_REFRESH_TICKETS=yes
   - WINBIND_USE_DEFAULT_DOMAIN=yes
   - BIND_INTERFACES_ONLY=true
   - BIND_INTERFACES=eth0 lo
   - WINBIND_REFRESH_TICKETS=false
   - WINBIND_USE_DEFAULT_DOMAIN=false
   - DEBUG=false
   - DEBUGLEVEL=0
   - NTPSERVERLIST=DC01
   - LOG_LEVEL=0
   - IDMIN=10000
   - IDMAX=999999
   - RFC2307=true
  domainname: ad.chaos
  hostname: samba-member
  extra_hosts:
   - "dc01.ad.chaos dc01:192.168.1.45"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - "./clients.conf:/etc/raddb/clients.conf"
   - "./users:/etc/raddb/users"
  networks:
   macvlan-samba:
    ipv4_address: 192.168.1.51
  cap_add:
   - SYS_TIME